### ISSUE TITLE
Rate limit error

### ISSUE THREAD

**Issue by hems** [ethfinex/efx-trustless-vol#6]
It seems that sometimes we get a ratelimit error from BFX API when fetching close prices for currencies.

here is some of the logs:

````
Feb 09 10:51:08 stats-sheet app/web.1:  (node:22) UnhandledPromiseRejectionWarning: StatusCodeError: 429 - ["error",11010,"ratelimit: error"] 
Feb 09 10:51:08 stats-sheet app/web.1:      at new StatusCodeError (/app/node_modules/request-promise-core/lib/errors.js:32:15) 
Feb 09 10:51:08 stats-sheet app/web.1:      at Request.plumbing.callback (/app/node_modules/request-promise-core/lib/plumbing.js:104:33) 
Feb 09 10:51:08 stats-sheet app/web.1:      at Request.RP$callback [as _callback] (/app/node_modules/request-promise-core/lib/plumbing.js:46:31) 
Feb 09 10:51:08 stats-sheet app/web.1:      at Request.self.callback (/app/node_modules/request/request.js:185:22) 
Feb 09 10:51:08 stats-sheet app/web.1:      at Request.emit (events.js:182:13) 
Feb 09 10:51:08 stats-sheet app/web.1:      at Request.<anonymous> (/app/node_modules/request/request.js:1161:10) 
Feb 09 10:51:09 stats-sheet app/web.1:      at Request.emit (events.js:182:13) 
Feb 09 10:51:09 stats-sheet app/web.1:      at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1083:12) 
Feb 09 10:51:09 stats-sheet app/web.1:      at Object.onceWrapper (events.js:273:13) 
Feb 09 10:51:09 stats-sheet app/web.1:      at IncomingMessage.emit (events.js:187:15) 
Feb 09 10:51:09 stats-sheet app/web.1:      at endReadableNT (_stream_readable.js:1090:12) 
Feb 09 10:51:09 stats-sheet app/web.1:      at process._tickCallback (internal/process/next_tick.js:63:19) 
Feb 09 10:51:09 stats-sheet app/web.1:  (node:22) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1) 
Feb 09 10:51:09 stats-sheet app/web.1:  (node:22) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**Comment by hems** [comment]
Since i just uploaded the cached file for all dates until today we should not hit the rate limit anymore as we will just be calculating new days using the cron job at midnight.

on top of that i added a retry logic that automatically sleeps for 500 ms before trying again when the rate limit happens.

that should keep things safe from now on.
